
package view;

import main.WinkelApplication;

/**
 * @version 1.0
 * @author Tjarco
 * 
 * Het hoofdmenu van de applicatie, alleen toegankelijk voor de medewerker.
 * Vanaf hier kan er naar de verschillende sub-menu's genavigeerd worden.
 * De sub-menu's zijn:
 * -Categorielijst
 * -Klantenoverzicht
 * -Productovericht
 * -Voorraad
 * -Rapporten
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbCatalogus = new javax.swing.JButton();
        jbGebruikers = new javax.swing.JButton();
        jbProducten = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbVoorraad = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jButton2.setText("jButton2");

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(main.WinkelApplication.BACKGROUND);
        jPanel2.setPreferredSize(new java.awt.Dimension(892, 70));

        jLabel14.setFont(main.WinkelApplication.TITEL);
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hoofdmenu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(819, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setFocusable(false);
        jPanel4.setMaximumSize(new java.awt.Dimension(1100, 300));
        jPanel4.setMinimumSize(new java.awt.Dimension(800, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 300));
        jPanel4.setRequestFocusEnabled(false);

        jbCatalogus.setFont(main.WinkelApplication.FONT_14_BOLD);
        jbCatalogus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/shoppingChart.png"))); // NOI18N
        jbCatalogus.setText("Catalogus");
        jbCatalogus.setBorderPainted(false);
        jbCatalogus.setContentAreaFilled(false);
        jbCatalogus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCatalogus.setFocusPainted(false);
        jbCatalogus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCatalogus.setMaximumSize(new java.awt.Dimension(150, 100));
        jbCatalogus.setPreferredSize(new java.awt.Dimension(150, 100));
        jbCatalogus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCatalogus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCatalogusActionPerformed(evt);
            }
        });

        jbGebruikers.setFont(main.WinkelApplication.FONT_14_BOLD);
        jbGebruikers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/klanten.png"))); // NOI18N
        jbGebruikers.setText("Gebruikers");
        jbGebruikers.setBorderPainted(false);
        jbGebruikers.setContentAreaFilled(false);
        jbGebruikers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGebruikers.setFocusPainted(false);
        jbGebruikers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbGebruikers.setMaximumSize(new java.awt.Dimension(150, 100));
        jbGebruikers.setPreferredSize(new java.awt.Dimension(150, 100));
        jbGebruikers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbGebruikers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGebruikersActionPerformed(evt);
            }
        });

        jbProducten.setFont(main.WinkelApplication.FONT_14_BOLD);
        jbProducten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/basketFull.png"))); // NOI18N
        jbProducten.setText("Producten");
        jbProducten.setToolTipText("");
        jbProducten.setBorderPainted(false);
        jbProducten.setContentAreaFilled(false);
        jbProducten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbProducten.setFocusPainted(false);
        jbProducten.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbProducten.setMaximumSize(new java.awt.Dimension(150, 100));
        jbProducten.setPreferredSize(new java.awt.Dimension(150, 100));
        jbProducten.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbProducten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductenActionPerformed(evt);
            }
        });

        jButton5.setFont(main.WinkelApplication.FONT_14_BOLD
        );
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/bar_graph.png"))); // NOI18N
        jButton5.setText("Rapporten");
        jButton5.setAlignmentX(0.5F);
        jButton5.setAlignmentY(0.0F);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(150, 100));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 100));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jbVoorraad.setFont(main.WinkelApplication.FONT_14_BOLD);
        jbVoorraad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons/Vooraad.png"))); // NOI18N
        jbVoorraad.setText("Voorraad");
        jbVoorraad.setToolTipText("");
        jbVoorraad.setBorderPainted(false);
        jbVoorraad.setContentAreaFilled(false);
        jbVoorraad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVoorraad.setFocusPainted(false);
        jbVoorraad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbVoorraad.setMaximumSize(new java.awt.Dimension(150, 100));
        jbVoorraad.setPreferredSize(new java.awt.Dimension(150, 100));
        jbVoorraad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbVoorraad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoorraadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbCatalogus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbGebruikers, javax.swing.GroupLayout.PREFERRED_SIZE, 164, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbProducten, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbVoorraad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbVoorraad, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProducten, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbCatalogus, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbGebruikers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(main.WinkelApplication.BACKGROUND);
        jPanel3.setPreferredSize(new java.awt.Dimension(892, 70));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCatalogusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCatalogusActionPerformed
        WinkelApplication.getInstance().showPanel(new CategoryList());
    }//GEN-LAST:event_jbCatalogusActionPerformed

    private void jbProductenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductenActionPerformed
        WinkelApplication.getInstance().showPanel(new ProductenOverzicht());
    }//GEN-LAST:event_jbProductenActionPerformed

    private void jbGebruikersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGebruikersActionPerformed
        WinkelApplication.getInstance().showPanel(new GebruikerOverzicht());
    }//GEN-LAST:event_jbGebruikersActionPerformed

    private void jbVoorraadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoorraadActionPerformed
        WinkelApplication.getInstance().showPanel(new Voorraad());
    }//GEN-LAST:event_jbVoorraadActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        WinkelApplication.getInstance().showPanel(new Rapporten());
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbCatalogus;
    private javax.swing.JButton jbGebruikers;
    private javax.swing.JButton jbProducten;
    private javax.swing.JButton jbVoorraad;
    // End of variables declaration//GEN-END:variables
}
